# Generated by Django 6.0.3 on 2026-04-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_textmodel_delete_bikemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextModel',
            new_name='TaskModel',
        ),
    ]
