# Generated by Django 6.0.3 on 2026-04-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_completedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=100)),
            ],
        ),
    ]
